import Footer from "./Footer.jsx";
import Navbar from "./Navbar.jsx";

const Template = ({ children, title }) => {
  return (
    <>
      <head>
        <title>{title}</title>
        <meta name="description" conent="Generated by create next app" />
        <link rel="icon" href="/favitcon.ico" />
      </head>
      <Navbar />
      <div className=" lg:px-24 text-white py-20 mt-8 p-12 bg-slate-800">
        {children}
      </div>
      <Footer />
    </>
  );
};
export default Template;
