export const projects = [
  {
    title: "Bukapedia",
    href: "https://bukapedia-three.vercel.app",
    images: "bukapedia.png",
    body: "fake store with cart featur",
    icons: ["react.svg", "tailwind.svg", "redux.svg"],
  },
  {
    title: "Weather App",
    href: "https://weatherapp-indol-nu.vercel.app",
    images: "weather.png",
    body: "website to see the weather in various regions.",
    icons: ["react.svg", "bootstrap.svg"],
  },
  {
    title: "Notes App",
    href: "https://mynotes-ku.vercel.app",
    images: "notes.png",
    body: "This website is for keeping your daily notes.",
    icons: ["react.svg", "tailwind.svg"],
  },
  {
    title: "Search Cars",
    href: "https://my-cars-showcase.vercel.app",
    images: "cars.png",
    body: "On this website there are various car specifications that you can see.",
    icons: ["next.svg", "typescript.svg", "tailwind.svg"],
  },
  {
    title: "Al-qur'an App",
    href: "https://my-al-quran.vercel.app",
    images: "al-quran.png",
    body: "website for reading the Al-Qur'an and audio is provided.",
    icons: ["react.svg", "tailwind.svg"],
  },
  {
    title: "Frontdev Company",
    href: "https://frontdevtech.vercel.app",
    images: "frontdev.png",
    body: "frontdev company profile website which provides digital services.",
    icons: ["html.svg", "css.svg", "javascript.svg"],
  },
  {
    title: "Calculator",
    href: "https://calculatorapp-gold.vercel.app",
    images: "calculator.png",
    body: "calculator as a website-based calculation tool.",
    icons: ["html.svg", "css.svg", "javascript.svg"],
  },
];
