export const projects = [
  {
    title: "Jimpit: Sistem Pengelolaan Tabungan Masyarakat Desa Babakan",
    href: "https://jimpit.my.id",
    images: "jimpit.png",
    body: "Sebuah Sistem yang Berfungsi Untuk Mengelola Jimpit di desa Babakan, Kecamatan Kawunganten",
    icons: ["laravel.svg", "mysql.svg", "bootstrap.svg"],
  },
  {
    title: "Bukapedia",
    href: "https://bukapedia-three.vercel.app",
    images: "bukapedia.png",
    body: "fake store with cart featur",
    icons: ["react.svg", "tailwind.svg", "redux.svg"],
  },
  {
    title: "Learning Management System",
    href: "",
    images: "lms.png",
    body: "Sistem Pengelolaan Pembelajaran",
    icons: ["php.svg", "laravel.svg", "mysql.svg", "next.svg", "tailwind.svg"],
  },
  {
    title: "Weather App",
    href: "https://weatherapp-indol-nu.vercel.app",
    images: "weather.png",
    body: "website to see the weather in various regions.",
    icons: ["react.svg", "bootstrap.svg"],
  },
  {
    title: "Notes App",
    href: "https://mynotes-ku.vercel.app",
    images: "notes.png",
    body: "This website is for keeping your daily notes.",
    icons: ["react.svg", "tailwind.svg"],
  },
  {
    title: "Cars Showcase",
    href: "https://my-cars-showcase.vercel.app",
    images: "cars.png",
    body: "On this website there are various car specifications that you can see.",
    icons: ["next.svg", "typescript.svg", "tailwind.svg"],
  },
  {
    title: "Al-qur'an App",
    href: "https://quran-green.vercel.app",
    images: "quran.png",
    body: "website for reading the Al-Qur'an and audio is provided.",
    icons: ["react.svg", "tailwind.svg"],
  },
];
